version: 1
timeout: "1m"

validators:
  # docs.github.com returns 403 if not in browser. Cannot curl as well.
  - regex: 'docs\.github\.com'
    type: "ignore"
  - regex: 'https:\/\/twitter.com\/PromOperator'
    type: ignore
